// generated by rosidl_typesupport_cyclonedds_c
@{
from rosidl_parser.definition import AbstractNestedType
from rosidl_parser.definition import Array
from rosidl_parser.definition import BasicType
from rosidl_parser.definition import Message
from rosidl_parser.definition import NamespacedType
from rosidl_pycommon import convert_camel_case_to_lower_case_underscore

messages = content.get_elements_of_type(Message)

def ros_c_name(type_):
    return '__'.join(type_.namespaced_name())

def dds_c_name(type_):
    return '_'.join(type_.namespaces) + '_dds__' + type_.name + '_'

def converter_name(type_, direction):
    return ros_c_name(type_) + '__' + direction

def conversion_lines(member, direction):
    from rosidl_parser.definition import Array
    from rosidl_parser.definition import BasicType
    from rosidl_parser.definition import NamespacedType
    from rosidl_typesupport_cyclonedds_c import is_supported_fixed_size_type

    def nested_converter_name(type_, nested_direction):
        return '__'.join(type_.namespaced_name()) + '__' + nested_direction

    field = member.name
    type_ = member.type
    if not is_supported_fixed_size_type(type_):
        raise RuntimeError(
            'rosidl_typesupport_cyclonedds_c Phase 4 supports only fixed-size '
            'scalars, arrays, and nested messages; unsupported member: ' + member.name)
    ros_expr = 'ros_sample->' + field
    dds_expr = 'dds_sample->' + field + '_'
    source = ros_expr if direction == 'ros_to_dds' else dds_expr
    destination = dds_expr if direction == 'ros_to_dds' else ros_expr
    lines = []
    if isinstance(type_, BasicType):
        lines.append(destination + ' = ' + source + ';')
    elif isinstance(type_, NamespacedType):
        lines.append('if (!' + nested_converter_name(type_, direction) +
                     '(&' + source + ', &' + destination + ')) {')
        lines.append('  return false;')
        lines.append('}')
    elif isinstance(type_, Array):
        lines.append('for (size_t index = 0U; index < ' + str(type_.size) + 'U; ++index) {')
        if isinstance(type_.value_type, BasicType):
            lines.append('  ' + destination + '[index] = ' + source + '[index];')
        else:
            lines.append('  if (!' + nested_converter_name(type_.value_type, direction) +
                         '(&' + source + '[index], &' + destination + '[index])) {')
            lines.append('    return false;')
            lines.append('  }')
        lines.append('}')
    return lines

include_parts = [package_name] + list(interface_path.parents[0].parts) + [
    'detail', convert_camel_case_to_lower_case_underscore(interface_path.stem)]
include_base = '/'.join(include_parts)
dependency_types = {}
for generated_message in messages:
    for generated_member in generated_message.structure.members:
        generated_type = generated_member.type
        if isinstance(generated_type, Array):
            generated_type = generated_type.value_type
        if isinstance(generated_type, NamespacedType):
            dependency_types[tuple(generated_type.namespaced_name())] = generated_type
}@
#include <stddef.h>
#include <string.h>

#include "@('/'.join([package_name] + list(interface_path.parents[0].parts) + [interface_path.stem + '_.h']))"
#include "@(include_base)__functions.h"
#include "@(include_base)__rosidl_typesupport_cyclonedds_c.h"
#include "@(include_base)__struct.h"
@[for dependency_type in [dependency_types[key] for key in sorted(dependency_types)]]@
#include "@('/'.join([*dependency_type.namespaces, 'detail', convert_camel_case_to_lower_case_underscore(dependency_type.name) + '__rosidl_typesupport_cyclonedds_c.h']))"
@[end for]@
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_cyclonedds_c/identifier.h"
#include "rosidl_typesupport_cyclonedds_c/message_type_support.h"
#include "rosidl_typesupport_interface/macros.h"

@[for message in messages]@
@{
ros_type = message.structure.namespaced_type
ros_name = ros_c_name(ros_type)
dds_name = dds_c_name(ros_type)
}@
bool @(ros_name)__ros_to_dds(const void * ros_message, void * dds_message)
{
  if (ros_message == NULL || dds_message == NULL) {
    return false;
  }
  const @(ros_name) * ros_sample = ros_message;
  @(dds_name) * dds_sample = dds_message;
@[for member in message.structure.members]@
@[  for line in conversion_lines(member, 'ros_to_dds')]@
  @(line)
@[  end for]@
@[end for]@
  return true;
}

bool @(ros_name)__dds_to_ros(const void * dds_message, void * ros_message)
{
  if (dds_message == NULL || ros_message == NULL) {
    return false;
  }
  const @(dds_name) * dds_sample = dds_message;
  @(ros_name) * ros_sample = ros_message;
@[for member in message.structure.members]@
@[  for line in conversion_lines(member, 'dds_to_ros')]@
  @(line)
@[  end for]@
@[end for]@
  return true;
}

static const rosidl_typesupport_cyclonedds_c__message_type_support_callbacks_t
@(ros_name)__callbacks = {
  "@('/'.join(ros_type.namespaced_name()))",
  "@('::'.join([*ros_type.namespaces, 'dds_', ros_type.name + '_']))",
  &@(dds_name[:-1])__desc,
  sizeof(@(ros_name)),
  sizeof(@(dds_name)),
  &@(ros_name)__ros_to_dds,
  &@(ros_name)__dds_to_ros,
};

static rosidl_message_type_support_t @(ros_name)__handle = {
  NULL,
  &@(ros_name)__callbacks,
  get_message_typesupport_handle_function,
  &@(ros_name)__get_type_hash,
  &@(ros_name)__get_type_description,
  &@(ros_name)__get_type_description_sources,
};

const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(
  rosidl_typesupport_cyclonedds_c,
  @(ros_type.namespaces[0]),
  @(ros_type.namespaces[1]),
  @(ros_type.name))()
{
  @(ros_name)__handle.typesupport_identifier =
    rosidl_typesupport_cyclonedds_c__identifier;
  return &@(ros_name)__handle;
}
@[end for]@
