<?xml version="1.0"?>
<package format="3">
  <name>rmw_cyclonedds_c</name>
  <version>0.1.0</version>
  <description>Profile-limited C implementation of the ROS 2 RMW interface backed by Cyclone DDS.</description>
  <maintainer email="fj-blanco@users.noreply.github.com">Javier Blanco</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cyclonedds</depend>
  <depend>rmw</depend>
  <depend>rosidl_runtime_c</depend>
  <depend>rosidl_typesupport_c</depend>
  <depend>rosidl_typesupport_cyclonedds_c</depend>
  <depend>std_msgs</depend>

  <test_depend condition="$ROS2_ZEPHYR_CROSS != 1">cyclonedds_c_test_msgs</test_depend>
  <test_depend condition="$ROS2_ZEPHYR_CROSS != 1">rcl</test_depend>
  <test_depend condition="$ROS2_ZEPHYR_CROSS != 1">rclc</test_depend>

  <member_of_group>rmw_implementation_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
