// SPDX-License-Identifier: Apache-2.0

// generated by rosidl_typesupport_cyclonedds_c
@{
from rosidl_parser.definition import Message
from rosidl_pycommon import convert_camel_case_to_lower_case_underscore
messages = content.get_elements_of_type(Message)
}@
#ifndef @('__'.join([package_name.upper(), *[p.upper() for p in interface_path.parents[0].parts], interface_path.stem.upper(), 'ROSIDL_TYPESUPPORT_CYCLONEDDS_C_H_']))
#define @('__'.join([package_name.upper(), *[p.upper() for p in interface_path.parents[0].parts], interface_path.stem.upper(), 'ROSIDL_TYPESUPPORT_CYCLONEDDS_C_H_']))

#include <stdbool.h>
#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_interface/macros.h"

#ifdef __cplusplus
extern "C"
{
#endif

@[for message in messages]@
bool @('__'.join(message.structure.namespaced_type.namespaced_name()))__ros_to_dds(
  const void * ros_message, void * dds_message);
bool @('__'.join(message.structure.namespaced_type.namespaced_name()))__dds_to_ros(
  const void * dds_message, void * ros_message);

const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(
  rosidl_typesupport_cyclonedds_c,
  @(message.structure.namespaced_type.namespaces[0]),
  @(message.structure.namespaced_type.namespaces[1]),
  @(message.structure.namespaced_type.name))();
@[end for]@

#ifdef __cplusplus
}
#endif

#endif
